#!/usr/local/bin/perl -w

print "Content-Type: application/xml\n\n";

my $URL = "http://" . $ENV{HTTP_HOST} . $ENV{REQUEST_URI};

use RDF::Query::Client;
 
 my $query = RDF::Query::Client
               ->new('DESCRIBE <'.$URL.'>');
 
my $iterator = $query->execute('http://linkeddata.systems:8890/sparql');

my $xml = $iterator->as_xml;
 
print '<?xml version="1.0" encoding="UTF-8" ?>'."\n";
print '<?xml-stylesheet type="text/xsl" href="http://linkeddata.systems/styles/phi.xsl" ?>'."\n";

$xml =~ s/\<\?xml.*\>\n//;
print $xml;


